{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-licors
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/LICORS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/LICORS/LICORS_{{ version }}.tar.gz
  sha256: 75f9aa6019f133d9967f53c4c8201744b10f46fc07eaab7e634b82290d492cc9

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fnn
    - r-matrix
    - r-rcolorbrewer
    - r-fields
    - r-locfit
    - r-mvtnorm
    - r-zoo
  run:
    - r-base
    - r-fnn
    - r-matrix
    - r-rcolorbrewer
    - r-fields
    - r-locfit
    - r-mvtnorm
    - r-zoo

test:
  commands:
    - $R -e "library('LICORS')"           # [not win]
    - "\"%R%\" -e \"library('LICORS')\""  # [win]

about:
  home: http://www.stat.cmu.edu/~gmg
  license: GPL-2.0-only
  summary: Estimates predictive states from spatio-temporal data and consequently can provide
    provably optimal forecasts. Currently this implementation supports an N-dimensional
    spatial grid observed over equally spaced time intervals. E.g. a video is a 2D spatial
    systems observed over time. This package implements mixed LICORS, has plotting tools
    (for (1+1)D and (2+1)D systems), and methods for optimal forecasting.  Due to memory
    limitations it is recommend to only analyze (1+1)D systems.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
